In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    'i love my dog',
    'I, love my cat',
    'you love my dog!',
    'Do you think my dog is amazing?'
]

tokenizer=Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentences)
word_index=tokenizer.word_index
print(word_index)

{'my': 1, 'love': 2, 'dog': 3, 'i': 4, 'you': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10}


In [ ]:
sequences = tokenizer.texts_to_sequences(sentences)
print('sequences avant padding:', sequences)

sequences avant padding: [[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padding = pad_sequences(sequences,
                        padding='post')
print("Word Index =", word_index)
print("\nsequences après padding:", padding)

Word Index = {'my': 1, 'love': 2, 'dog': 3, 'i': 4, 'you': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10}

sequences après padding: [[ 4  2  1  3  0  0  0]
 [ 4  2  1  6  0  0  0]
 [ 5  2  1  3  0  0  0]
 [ 7  5  8  1  3  9 10]]


In [ ]:
sentences1 = ['i love my computer']
sequences1 = tokenizer.texts_to_sequences(sentences1)
print('sequences avant padding:', sequences1)
padding1 = pad_sequences(sequences1)
print(padding1)

sequences avant padding: [[4, 2, 1]]
[[4 2 1]]


In [ ]:
text_vectorizer = tf.keras.layers.TextVectorization(
    max_tokens=None,
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    ngrams=None,
    output_mode='int',
    output_sequence_length=None
)

In [ ]:
text_vectorizer.adapt(sentences)

In [ ]:
text_vectorizer(sentences)

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[4, 3, 2, 5],
       [4, 3, 2, 7],
       [6, 3, 2, 5]])>

In [ ]:
tf.random.set_seed(42)
from tensorflow.keras import layers

embedding = layers.Embedding(
    input_dim=10,
    output_dim=20,
    embeddings_initializer="zeros",

)

In [ ]:
sentences_nlp = [
    'i love my job',
    'you are beautiful',
    'i am writing my code',
    'i love my class',
    'we are eating our lunch',
    'the weather is sunny',
    'i hate my job',
    'you are angry',
    'the weather is rainy',
    'we are eating our dinner',
    'the food was cold and tasteless',
    'i like my new environment',
    'my team has lost the game',
    'i still havent found an internship',
    'you find it hard to wake up the morning',
    'my pc is not working correctly',
    'the pollution is destroying our planet',
    'it is not cold outside',
    'the bank is being robbed',
    'the ai is taking over the world'
]

labels = [
    'bonne','bonne','bonne','bonne','bonne','bonne',
    'mauvaise','mauvaise','bonne','bonne','mauvaise',
    'bonne','mauvaise','mauvaise','mauvaise','mauvaise','mauvaise','bonne','mauvaise','mauvaise'
]



In [ ]:
tokenizer_nlp = Tokenizer(num_words=100)
tokenizer_nlp.fit_on_texts(sentences_nlp)
word_index_nlp = tokenizer_nlp.word_index
print(word_index_nlp)

{'the': 1, 'my': 2, 'is': 3, 'i': 4, 'are': 5, 'you': 6, 'our': 7, 'love': 8, 'job': 9, 'we': 10, 'eating': 11, 'weather': 12, 'cold': 13, 'it': 14, 'not': 15, 'beautiful': 16, 'am': 17, 'writing': 18, 'code': 19, 'class': 20, 'lunch': 21, 'sunny': 22, 'hate': 23, 'angry': 24, 'rainy': 25, 'dinner': 26, 'food': 27, 'was': 28, 'and': 29, 'tasteless': 30, 'like': 31, 'new': 32, 'environment': 33, 'team': 34, 'has': 35, 'lost': 36, 'game': 37, 'still': 38, 'havent': 39, 'found': 40, 'an': 41, 'internship': 42, 'find': 43, 'hard': 44, 'to': 45, 'wake': 46, 'up': 47, 'morning': 48, 'pc': 49, 'working': 50, 'correctly': 51, 'pollution': 52, 'destroying': 53, 'planet': 54, 'outside': 55, 'bank': 56, 'being': 57, 'robbed': 58, 'ai': 59, 'taking': 60, 'over': 61, 'world': 62}


In [ ]:
sequences_nlp = tokenizer_nlp.texts_to_sequences(sentences_nlp)
print(sequences_nlp)

[[4, 8, 2, 9], [6, 5, 16], [4, 17, 18, 2, 19], [4, 8, 2, 20], [10, 5, 11, 7, 21], [1, 12, 3, 22], [4, 23, 2, 9], [6, 5, 24], [1, 12, 3, 25], [10, 5, 11, 7, 26], [1, 27, 28, 13, 29, 30], [4, 31, 2, 32, 33], [2, 34, 35, 36, 1, 37], [4, 38, 39, 40, 41, 42], [6, 43, 14, 44, 45, 46, 47, 1, 48], [2, 49, 3, 15, 50, 51], [1, 52, 3, 53, 7, 54], [14, 3, 15, 13, 55], [1, 56, 3, 57, 58], [1, 59, 3, 60, 61, 1, 62]]


In [ ]:
padding_nlp = pad_sequences(sequences_nlp)
print(padding_nlp)

[[ 0  0  0  0  0  4  8  2  9]
 [ 0  0  0  0  0  0  6  5 16]
 [ 0  0  0  0  4 17 18  2 19]
 [ 0  0  0  0  0  4  8  2 20]
 [ 0  0  0  0 10  5 11  7 21]
 [ 0  0  0  0  0  1 12  3 22]
 [ 0  0  0  0  0  4 23  2  9]
 [ 0  0  0  0  0  0  6  5 24]
 [ 0  0  0  0  0  1 12  3 25]
 [ 0  0  0  0 10  5 11  7 26]
 [ 0  0  0  1 27 28 13 29 30]
 [ 0  0  0  0  4 31  2 32 33]
 [ 0  0  0  2 34 35 36  1 37]
 [ 0  0  0  4 38 39 40 41 42]
 [ 6 43 14 44 45 46 47  1 48]
 [ 0  0  0  2 49  3 15 50 51]
 [ 0  0  0  1 52  3 53  7 54]
 [ 0  0  0  0 14  3 15 13 55]
 [ 0  0  0  0  1 56  3 57 58]
 [ 0  0  1 59  3 60 61  1 62]]


## Prepare Data for Classification




In [ ]:
import numpy as np

numerical_labels = []
for label in labels:
    if label == 'bonne':
        numerical_labels.append(1)
    else:
        numerical_labels.append(0)

numerical_labels = np.array(numerical_labels)

print("Original labels:", labels)
print("Numerical labels:", numerical_labels)

Original labels: ['bonne', 'bonne', 'bonne', 'bonne', 'bonne', 'bonne', 'mauvaise', 'mauvaise', 'bonne', 'bonne', 'mauvaise', 'bonne', 'mauvaise', 'mauvaise', 'mauvaise', 'mauvaise', 'mauvaise', 'bonne', 'mauvaise', 'mauvaise']
Numerical labels: [1 1 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0]


In [ ]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(padding_nlp, numerical_labels, test_size=0.2, random_state=42)

# print(f"X_train shape: {X_train.shape}")
# print(f"X_test shape: {X_test.shape}")
# print(f"y_train shape: {y_train.shape}")
# print(f"y_test shape: {y_test.shape}")

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense

vocab_size = len(tokenizer_nlp.word_index) + 1
embedding_dim = 32
max_len = padding_nlp.shape[1] # Keep max_len to define input shape

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim), # Removed input_length as it's deprecated
    GlobalAveragePooling1D(),
    Dropout(0.5),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Explicitly build the model with the expected input shape
# The input shape for a sequence model is (batch_size, sequence_length)
# None for batch_size indicates it can handle any batch size
model.build(input_shape=(None, max_len))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 9, 32)          │         2,016 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_6      │ (None, 32)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,561 (10.00 KB)

 Trainable params: 2,561 (10.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test))
print("Model training complete.")

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.4375 - loss: 0.6935 - val_accuracy: 0.7500 - val_loss: 0.6891
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.3750 - loss: 0.6921 - val_accuracy: 0.7500 - val_loss: 0.6892
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.5000 - loss: 0.6925 - val_accuracy: 0.7500 - val_loss: 0.6894
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.3125 - loss: 0.6959 - val_accuracy: 0.7500 - val_loss: 0.6900
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5000 - loss: 0.6912 - val_accuracy: 0.7500 - val_loss: 0.6905
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.4375 - loss: 0.6902 - val_accuracy: 0.5000 - val_loss: 0.6912
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6875 - loss: 0.6885 - val_accuracy: 0.5000 - val_loss: 0.6918
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8125 - loss: 0.6855 - val_accuracy: 0.5000 - val_loss: 0.6

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7500 - loss: 0.6886
Test Loss: 0.6886
Test Accuracy: 0.7500


In [ ]:
new_sentence_str = 'i hate life'
new_sentence_list = [new_sentence_str]

# Convert the new sentence into a sequence of numbers
new_sequence = tokenizer_nlp.texts_to_sequences(new_sentence_list)

# Pad the new sequence to the max_len used during training
# Ensure new_sequence is a list of lists if tokenizer_nlp outputs a list of lists
new_padded_sequence = pad_sequences(new_sequence, maxlen=max_len)

# Use the trained model to predict the class of the padded new sequence
prediction_probability = model.predict(new_padded_sequence)[0][0]

# Interpret the prediction
predicted_label = 'bonne' if prediction_probability >= 0.5 else 'mauvaise'

print(f"New Sentence: '{new_sentence_str}'")
print(f"Prediction Probability: {prediction_probability:.4f}")
print(f"Predicted Label: {predicted_label}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
New Sentence: 'i hate life'
Prediction Probability: 0.5160
Predicted Label: bonne


In [ ]:
#sarcasm.json
!gdown --id 1xRU3xY5-tkiPGvlz5xBJ18_pHWSRzI4v

import json
import pandas as pd
data = pd.read_json('sarcasm.json')
data.head()

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1xRU3xY5-tkiPGvlz5xBJ18_pHWSRzI4v
To: /content/sarcasm.json
100% 5.64M/5.64M [00:00<00:00, 34.8MB/s]


,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://local.theonion.com/mom-starting-to-fea...,mom starting to fear son's web series closest ...,1
3,https://politics.theonion.com/boehner-just-wan...,"boehner just wants wife to listen, not come up...",1
4,https://www.huffingtonpost.com/entry/jk-rowlin...,j.k. rowling wishes snape happy birthday in th...,0


In [ ]:
import re

def clean_text(text):
    text = re.sub(r'http\S+|www\S+|https\S+', '', text) # Remove URLs
    text = text.lower() # Convert to lowercase    # remove special characters
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

data['cleaned_headline'] = data['headline'].apply(clean_text)

print("Original Headlines:")
print(data['headline'].head())
print("\nCleaned Headlines:")
print(data['cleaned_headline'].head())

Original Headlines:
0    former versace store clerk sues over secret 'b...
1    the 'roseanne' revival catches up to our thorn...
2    mom starting to fear son's web series closest ...
3    boehner just wants wife to listen, not come up...
4    j.k. rowling wishes snape happy birthday in th...
Name: headline, dtype: object

Cleaned Headlines:
0    former versace store clerk sues over secret bl...
1    the roseanne revival catches up to our thorny ...
2    mom starting to fear sons web series closest t...
3    boehner just wants wife to listen not come up ...
4    jk rowling wishes snape happy birthday in the ...
Name: cleaned_headline, dtype: object


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Initialize a Tokenizer
# Using a reasonable num_words for a larger dataset
# The actual vocabulary size will be len(tokenizer.word_index) + 1
vocab_size_limit = 10000 # Example: limit to top 10000 words
tokenizer = Tokenizer(num_words=vocab_size_limit, oov_token='<unk>')

# Fit the tokenizer on the cleaned headlines
tokenizer.fit_on_texts(data['cleaned_headline'])

# Convert headlines to sequences
sequences = tokenizer.texts_to_sequences(data['cleaned_headline'])

# Determine the maximum sequence length
max_sequence_len = max([len(x) for x in sequences])

# Pad the sequences to a uniform length
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_len, padding='post', truncating='post')

# Get the vocabulary size (actual unique words + 1 for OOV token)
vocabulary_size = len(tokenizer.word_index) + 1

print(f"Vocabulary size: {vocabulary_size}")
print(f"Maximum sequence length: {max_sequence_len}")
print(f"Shape of padded sequences: {padded_sequences.shape}")
print("First 5 original headlines:")
print(data['cleaned_headline'].head().to_list())
print("\nFirst 5 sequences:")
print(sequences[:5])
print("\nFirst 5 padded sequences:")
print(padded_sequences[:5])


Vocabulary size: 28386
Maximum sequence length: 39
Shape of padded sequences: (26709, 39)
First 5 original headlines:
['former versace store clerk sues over secret black code for minority shoppers', 'the roseanne revival catches up to our thorny political mood for better and worse', 'mom starting to fear sons web series closest thing she will have to grandchild', 'boehner just wants wife to listen not come up with alternative debtreduction ideas', 'jk rowling wishes snape happy birthday in the most magical way']

First 5 sequences:
[[294, 1, 797, 3552, 2242, 48, 360, 93, 2139, 6, 2511, 8288], [4, 8289, 3284, 2685, 28, 2, 156, 8290, 393, 2875, 6, 241, 9, 952], [140, 818, 2, 798, 1096, 2047, 570, 4633, 199, 139, 39, 46, 2, 1], [1463, 35, 209, 426, 2, 1648, 29, 306, 28, 10, 3285, 1, 863], [4634, 4635, 891, 1, 571, 553, 5, 4, 91, 1243, 92]]

First 5 padded sequences:
[[ 294    1  797 3552 2242   48  360   93 2139    6 2511 8288    0    0
     0    0    0    0    0    0    0    0    0    0 

In [ ]:
import numpy as np

# Extract the 'is_sarcastic' column
labels = data['is_sarcastic'].to_numpy()

# Print the first few elements and the shape of the labels array
print("First 5 labels:", labels[:5])
print("Shape of labels array:", labels.shape)

First 5 labels: [0 0 1 1 0]
Shape of labels array: (26709,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (21367, 39)
X_test shape: (5342, 39)
y_train shape: (21367,)
y_test shape: (5342,)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense

# 3. Initialize a Sequential model
model = Sequential()

# 4. Add an Embedding layer
# Using vocabulary_size determined from previous steps
model.add(Embedding(input_dim=vocabulary_size, output_dim=32))

# 5. Add a GlobalAveragePooling1D layer
model.add(GlobalAveragePooling1D())

# 6. Add a Dense layer with 1 unit and sigmoid activation
model.add(Dense(1, activation='sigmoid'))

# Explicitly build the model with the expected input shape
# The input shape for a sequence model is (batch_size, sequence_length)
# None for batch_size indicates it can handle any batch size
model.build(input_shape=(None, max_sequence_len))

# 7. Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 8. Print the model summary
model.summary()


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)        │ (None, 39, 32)         │       908,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_10     │ (None, 32)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 908,385 (3.47 MB)

 Trainable params: 908,385 (3.47 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))
print("Model training complete.")

Epoch 1/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.5886 - loss: 0.6635 - val_accuracy: 0.7125 - val_loss: 0.5452
Epoch 2/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.7991 - loss: 0.4939 - val_accuracy: 0.8270 - val_loss: 0.4255
Epoch 3/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.8512 - loss: 0.3854 - val_accuracy: 0.8409 - val_loss: 0.3800
Epoch 4/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.8783 - loss: 0.3254 - val_accuracy: 0.8482 - val_loss: 0.3563
Epoch 5/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.8926 - loss: 0.2895 - val_accuracy: 0.8564 - val_loss: 0.3419
Epoch 6/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 11s 12ms/step - accuracy: 0.9042 - loss: 0.2612 - val_accuracy: 0.8555 - val_loss: 0.3371
Epoch 7/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.9079 - loss: 0.2418 - val_accuracy: 0.8570 - val_loss: 0.3342
Epoch 8/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9220 - loss: 0.2139 - val_ac

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

167/167 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3379
Test Loss: 0.3412
Test Accuracy: 0.8572


In [ ]:
new_headline = "i just love Mondays, they're always so productive and exciting!"

# 2. Apply the clean_text function
cleaned_new_headline = clean_text(new_headline)

# 3. Convert the cleaned new headline into a sequence of numbers
# Ensure it's passed as a list
new_sequence = tokenizer.texts_to_sequences([cleaned_new_headline])

# 4. Pad the generated sequence to the max_sequence_len
new_padded_sequence = pad_sequences(new_sequence, maxlen=max_sequence_len, padding='post', truncating='post')

# 5. Use the trained model to predict the class of the padded new sequence
prediction_probability = model.predict(new_padded_sequence)[0][0]

# 6. Interpret the prediction
predicted_label = 'sarcastic' if prediction_probability >= 0.5 else 'not sarcastic'

# 7. Print the results
print(f"New Headline: '{new_headline}'")
print(f"Cleaned Headline: '{cleaned_new_headline}'")
print(f"Prediction Probability: {prediction_probability:.4f}")
print(f"Predicted Label: {predicted_label}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
New Headline: 'i just love Mondays, they're always so productive and exciting!'
Cleaned Headline: 'i just love mondays theyre always so productive and exciting'
Prediction Probability: 0.0306
Predicted Label: not sarcastic


In [ ]:
new_headline2 = "researchers develop faster method for detecting early-stage diseases"

# 2. Apply the clean_text function
cleaned_new_headline2 = clean_text(new_headline2)

# 3. Convert the cleaned new headline into a sequence of numbers
# Ensure it's passed as a list
new_sequence2 = tokenizer.texts_to_sequences([cleaned_new_headline2])

# 4. Pad the generated sequence to the max_sequence_len
new_padded_sequence2 = pad_sequences(new_sequence2, maxlen=max_sequence_len, padding='post', truncating='post')

# 5. Use the trained model to predict the class of the padded new sequence
prediction_probability2 = model.predict(new_padded_sequence2)[0][0]

# 6. Interpret the prediction
predicted_label2 = 'sarcastic' if prediction_probability2 >= 0.5 else 'not sarcastic'

# 7. Print the results
print(f"New Headline: '{new_headline2}'")
print(f"Cleaned Headline: '{cleaned_new_headline2}'")
print(f"Prediction Probability: {prediction_probability2:.4f}")
print(f"Predicted Label: {predicted_label2}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
New Headline: 'researchers develop faster method for detecting early-stage diseases'
Cleaned Headline: 'researchers develop faster method for detecting earlystage diseases'
Prediction Probability: 0.7727
Predicted Label: sarcastic


## Build and Compile Model (without Embedding)



In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense

# Get the maximum sequence length from the previous steps
# max_sequence_len is already available from the kernel state (max_sequence_len: 39)

# 2. Initialize an empty Sequential model
model_no_embedding = Sequential()

# 3. Add a Flatten layer as the first layer to the model
#    Specify the input_shape to match the shape of the padded sequences
model_no_embedding.add(Flatten(input_shape=(max_sequence_len,)))

# 4. Add a Dense layer with a suitable number of units and an activation function
model_no_embedding.add(Dense(32, activation='relu'))

# 5. Add a final Dense layer with 1 unit and 'sigmoid' activation for binary classification
model_no_embedding.add(Dense(1, activation='sigmoid'))

# 6. Compile the model
model_no_embedding.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 7. Print the model's summary
model_no_embedding.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 39)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 32)             │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313 (5.13 KB)

 Trainable params: 1,313 (5.13 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense

# Get the maximum sequence length from the previous steps
# max_sequence_len is already available from the kernel state (max_sequence_len: 39)

# 2. Initialize an empty Sequential model
model_no_embedding = Sequential()

# 3. Add a Flatten layer as the first layer to the model
#    Specify the input_shape to match the shape of the padded sequences
model_no_embedding.add(Flatten(input_shape=(max_sequence_len,)))

# 4. Add a Dense layer with a suitable number of units and an activation function
model_no_embedding.add(Dense(32, activation='relu'))

# 5. Add a final Dense layer with 1 unit and 'sigmoid' activation for binary classification
model_no_embedding.add(Dense(1, activation='sigmoid'))

# 6. Compile the model
model_no_embedding.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 7. Print the model's summary
model_no_embedding.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)             │ (None, 39)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 32)             │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313 (5.13 KB)

 Trainable params: 1,313 (5.13 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Flatten, Dense

# Get the maximum sequence length from the previous steps
# max_sequence_len is already available from the kernel state (max_sequence_len: 39)

# 2. Define the Input layer explicitly
inputs = tf.keras.Input(shape=(max_sequence_len,))

# 3. Add a Flatten layer as the first layer to the model
flatten_layer = Flatten()(inputs)

# 4. Add a Dense layer with a suitable number of units and an activation function
dense_layer_1 = Dense(32, activation='relu')(flatten_layer)

# 5. Add a final Dense layer with 1 unit and 'sigmoid' activation for binary classification
outputs = Dense(1, activation='sigmoid')(dense_layer_1)

# Create the model using the Functional API
model_no_embedding = Model(inputs=inputs, outputs=outputs)

# 6. Compile the model
model_no_embedding.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 7. Print the model's summary
model_no_embedding.summary()


Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_9 (InputLayer)      │ (None, 39)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 39)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 32)             │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313 (5.13 KB)

 Trainable params: 1,313 (5.13 KB)

 Non-trainable params: 0 (0.00 B)

## Train Model (without Embedding)




In [ ]:
history_no_embedding = model_no_embedding.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))
print("Model without embedding training complete.")

Epoch 1/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.5018 - loss: 188.5797 - val_accuracy: 0.5352 - val_loss: 30.1778
Epoch 2/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5191 - loss: 26.9339 - val_accuracy: 0.4998 - val_loss: 20.2607
Epoch 3/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5283 - loss: 17.6832 - val_accuracy: 0.4897 - val_loss: 15.3882
Epoch 4/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5272 - loss: 13.9918 - val_accuracy: 0.5129 - val_loss: 10.6674
Epoch 5/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5277 - loss: 10.1195 - val_accuracy: 0.5075 - val_loss: 8.5453
Epoch 6/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5388 - loss: 8.0115 - val_accuracy: 0.5635 - val_loss: 9.5353
Epoch 7/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5352 - loss: 6.4833 - val_accuracy: 0.5395 - val_loss: 4.7800
Epoch 8/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5365 - loss: 4.6144 - val_ac

In [ ]:
loss_no_embedding, accuracy_no_embedding = model_no_embedding.evaluate(X_test, y_test)
print(f"Test Loss (without embedding): {loss_no_embedding:.4f}")
print(f"Test Accuracy (without embedding): {accuracy_no_embedding:.4f}")

167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5165 - loss: 2.8028
Test Loss (without embedding): 2.7572
Test Accuracy (without embedding): 0.5268


In [ ]:
new_headline_no_embedding = "i just love Mondays, they're always so productive and exciting!"

# 2. Apply the clean_text function
cleaned_new_headline_no_embedding = clean_text(new_headline_no_embedding)

# 3. Convert the cleaned new headline into a sequence of numbers
# Ensure it's passed as a list
new_sequence_no_embedding = tokenizer.texts_to_sequences([cleaned_new_headline_no_embedding])

# 4. Pad the generated sequence to the max_sequence_len
new_padded_sequence_no_embedding = pad_sequences(new_sequence_no_embedding, maxlen=max_sequence_len, padding='post', truncating='post')

# 5. Use the trained model to predict the class of the padded new sequence
prediction_probability_no_embedding = model_no_embedding.predict(new_padded_sequence_no_embedding)[0][0]

# 6. Interpret the prediction
predicted_label_no_embedding = 'sarcastic' if prediction_probability_no_embedding >= 0.5 else 'not sarcastic'

# 7. Print the results
print(f"New Headline: '{new_headline_no_embedding}'")
print(f"Cleaned Headline: '{cleaned_new_headline_no_embedding}'")
print(f"Prediction Probability (no embedding): {prediction_probability_no_embedding:.4f}")
print(f"Predicted Label (no embedding): {predicted_label_no_embedding}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
New Headline: 'i just love Mondays, they're always so productive and exciting!'
Cleaned Headline: 'i just love mondays theyre always so productive and exciting'
Prediction Probability (no embedding): 0.0002
Predicted Label (no embedding): not sarcastic


In [ ]:
new_headline_no_embedding2 = "researchers develop faster method for detecting early-stage diseases"

# 2. Apply the clean_text function
cleaned_new_headline_no_embedding2 = clean_text(new_headline_no_embedding2)

# 3. Convert the cleaned new headline into a sequence of numbers
# Ensure it's passed as a list
new_sequence_no_embedding2 = tokenizer.texts_to_sequences([cleaned_new_headline_no_embedding2])

# 4. Pad the generated sequence to the max_sequence_len
new_padded_sequence_no_embedding2 = pad_sequences(new_sequence_no_embedding2, maxlen=max_sequence_len, padding='post', truncating='post')

# 5. Use the trained model to predict the class of the padded new sequence
prediction_probability_no_embedding2 = model_no_embedding.predict(new_padded_sequence_no_embedding2)[0][0]

# 6. Interpret the prediction
predicted_label_no_embedding2 = 'sarcastic' if prediction_probability_no_embedding2 >= 0.5 else 'not sarcastic'

# 7. Print the results
print(f"New Headline: '{new_headline_no_embedding2}'")
print(f"Cleaned Headline: '{cleaned_new_headline_no_embedding2}'")
print(f"Prediction Probability (no embedding): {prediction_probability_no_embedding2:.4f}")
print(f"Predicted Label (no embedding): {predicted_label_no_embedding2}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
New Headline: 'researchers develop faster method for detecting early-stage diseases'
Cleaned Headline: 'researchers develop faster method for detecting earlystage diseases'
Prediction Probability (no embedding): 0.0385
Predicted Label (no embedding): not sarcastic


In [ ]:
new_headline_embedding_comparison1 = "i just love Mondays, they're always so productive and exciting!"
new_headline_embedding_comparison2 = "researchers develop faster method for detecting early-stage diseases"

# Preprocess the first new headline for the embedding model
cleaned_headline_embedding1 = clean_text(new_headline_embedding_comparison1)
sequence_embedding1 = tokenizer.texts_to_sequences([cleaned_headline_embedding1])
padded_sequence_embedding1 = pad_sequences(sequence_embedding1, maxlen=max_sequence_len, padding='post', truncating='post')

# Predict with the embedding model
prediction_prob_embedding1 = model.predict(padded_sequence_embedding1)[0][0]
predicted_label_embedding1 = 'sarcastic' if prediction_prob_embedding1 >= 0.5 else 'not sarcastic'

# Preprocess the second new headline for the embedding model
cleaned_headline_embedding2 = clean_text(new_headline_embedding_comparison2)
sequence_embedding2 = tokenizer.texts_to_sequences([cleaned_headline_embedding2])
padded_sequence_embedding2 = pad_sequences(sequence_embedding2, maxlen=max_sequence_len, padding='post', truncating='post')

# Predict with the embedding model
prediction_prob_embedding2 = model.predict(padded_sequence_embedding2)[0][0]
predicted_label_embedding2 = 'sarcastic' if prediction_prob_embedding2 >= 0.5 else 'not sarcastic'

print(f"--- Embedding Model Predictions ---")
print(f"New Headline 1: '{new_headline_embedding_comparison1}'")
print(f"Cleaned Headline 1: '{cleaned_headline_embedding1}'")
print(f"Prediction Probability (embedding model): {prediction_prob_embedding1:.4f}")
print(f"Predicted Label (embedding model): {predicted_label_embedding1}")

print(f"\nNew Headline 2: '{new_headline_embedding_comparison2}'")
print(f"Cleaned Headline 2: '{cleaned_headline_embedding2}'")
print(f"Prediction Probability (embedding model): {prediction_prob_embedding2:.4f}")
print(f"Predicted Label (embedding model): {predicted_label_embedding2}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
--- Embedding Model Predictions ---
New Headline 1: 'i just love Mondays, they're always so productive and exciting!'
Cleaned Headline 1: 'i just love mondays theyre always so productive and exciting'
Prediction Probability (embedding model): 0.0306
Predicted Label (embedding model): not sarcastic

New Headline 2: 'researchers develop faster method for detecting early-stage diseases'
Cleaned Headline 2: 'researchers develop faster method for detecting earlystage diseases'
Prediction Probability (embedding model): 0.7727
Predicted Label (embedding model): sarcastic


## Build and Compile Model (with Embedding)




In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense

# vocabulary_size and max_sequence_len are available from previous steps
# vocabulary_size: 28386, max_sequence_len: 39

# 1. Define the Input layer explicitly
inputs_with_embedding = tf.keras.Input(shape=(max_sequence_len,))

# 2. Add an Embedding layer
# Using vocabulary_size determined from previous steps
embedding_layer = Embedding(input_dim=vocabulary_size, output_dim=32)(inputs_with_embedding)

# 3. Add a GlobalAveragePooling1D layer
global_avg_pooling_layer = GlobalAveragePooling1D()(embedding_layer)

# 4. Add a Dense output layer with 1 unit and 'sigmoid' activation for binary classification
outputs_with_embedding = Dense(1, activation='sigmoid')(global_avg_pooling_layer)

# Create the model using the Functional API
model_with_embedding = Model(inputs=inputs_with_embedding, outputs=outputs_with_embedding)

# 5. Compile the model
model_with_embedding.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 6. Print the model's summary
model_with_embedding.summary()


Model: "functional_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_10 (InputLayer)     │ (None, 39)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_11 (Embedding)        │ (None, 39, 32)         │       908,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_11     │ (None, 32)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 908,385 (3.47 MB)

 Trainable params: 908,385 (3.47 MB)

 Non-trainable params: 0 (0.00 B)

## Train Model (with Embedding)



In [ ]:
history_with_embedding = model_with_embedding.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))
print("Model with embedding training complete.")

Epoch 1/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.5890 - loss: 0.6654 - val_accuracy: 0.7417 - val_loss: 0.5453
Epoch 2/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.8010 - loss: 0.4996 - val_accuracy: 0.8186 - val_loss: 0.4328
Epoch 3/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.8485 - loss: 0.3895 - val_accuracy: 0.8414 - val_loss: 0.3817
Epoch 4/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.8739 - loss: 0.3325 - val_accuracy: 0.8334 - val_loss: 0.3736
Epoch 5/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.8903 - loss: 0.2874 - val_accuracy: 0.8579 - val_loss: 0.3414
Epoch 6/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.9032 - loss: 0.2599 - val_accuracy: 0.8579 - val_loss: 0.3358
Epoch 7/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9160 - loss: 0.2346 - val_accuracy: 0.8607 - val_loss: 0.3305
Epoch 8/10
668/668 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.9195 - loss: 0.2163 - val_acc

## Evaluate Model Performance (with Embedding)



In [ ]:
loss_with_embedding, accuracy_with_embedding = model_with_embedding.evaluate(X_test, y_test)
print(f"Test Loss (with embedding): {loss_with_embedding:.4f}")
print(f"Test Accuracy (with embedding): {accuracy_with_embedding:.4f}")

167/167 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8567 - loss: 0.3445
Test Loss (with embedding): 0.3471
Test Accuracy (with embedding): 0.8559


## Make Predictions (Inference with best model)



In [ ]:
new_headline_for_inference = "Great news! My internet just went down right before my online exam! So convenient."

# 2. Apply the clean_text function
cleaned_new_headline_for_inference = clean_text(new_headline_for_inference)

# 3. Convert the cleaned new headline into a sequence of numbers
# Ensure it's passed as a list
new_sequence_for_inference = tokenizer.texts_to_sequences([cleaned_new_headline_for_inference])

# 4. Pad the generated sequence to the max_sequence_len
new_padded_sequence_for_inference = pad_sequences(new_sequence_for_inference, maxlen=max_sequence_len, padding='post', truncating='post')

# 5. Use the trained model to predict the class of the padded new sequence
prediction_probability_for_inference = model_with_embedding.predict(new_padded_sequence_for_inference)[0][0]

# 6. Interpret the prediction
predicted_label_for_inference = 'sarcastic' if prediction_probability_for_inference >= 0.5 else 'not sarcastic'

# 7. Print the results
print(f"New Headline: '{new_headline_for_inference}'")
print(f"Cleaned Headline: '{cleaned_new_headline_for_inference}'")
print(f"Prediction Probability (with embedding): {prediction_probability_for_inference:.4f}")
print(f"Predicted Label (with embedding): {predicted_label_for_inference}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
New Headline: 'Great news! My internet just went down right before my online exam! So convenient.'
Cleaned Headline: 'great news my internet just went down right before my online exam so convenient'
Prediction Probability (with embedding): 0.5490
Predicted Label (with embedding): sarcastic


**Reasoning**:
To further demonstrate the prediction capabilities of the `model_with_embedding`, I will make another prediction using a different new headline, following the same preprocessing and prediction steps as the previous cell.



In [ ]:
new_headline_for_inference2 = "The new AI assistant is so good, it just deleted all my important files! What a helper."

# 2. Apply the clean_text function
cleaned_new_headline_for_inference2 = clean_text(new_headline_for_inference2)

# 3. Convert the cleaned new headline into a sequence of numbers
# Ensure it's passed as a list
new_sequence_for_inference2 = tokenizer.texts_to_sequences([cleaned_new_headline_for_inference2])

# 4. Pad the generated sequence to the max_sequence_len
new_padded_sequence_for_inference2 = pad_sequences(new_sequence_for_inference2, maxlen=max_sequence_len, padding='post', truncating='post')

# 5. Use the trained model to predict the class of the padded new sequence
prediction_probability_for_inference2 = model_with_embedding.predict(new_padded_sequence_for_inference2)[0][0]

# 6. Interpret the prediction
predicted_label_for_inference2 = 'sarcastic' if prediction_probability_for_inference2 >= 0.5 else 'not sarcastic'

# 7. Print the results
print(f"New Headline: '{new_headline_for_inference2}'")
print(f"Cleaned Headline: '{cleaned_new_headline_for_inference2}'")
print(f"Prediction Probability (with embedding): {prediction_probability_for_inference2:.4f}")
print(f"Predicted Label (with embedding): {predicted_label_for_inference2}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
New Headline: 'The new AI assistant is so good, it just deleted all my important files! What a helper.'
Cleaned Headline: 'the new ai assistant is so good it just deleted all my important files what a helper'
Prediction Probability (with embedding): 0.0446
Predicted Label (with embedding): not sarcastic
